CREATE TABLE "blend_cuts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "blend_cuts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"description" text NOT NULL,
	CONSTRAINT "blend_cuts_description_unique" UNIQUE("description")
);
--> statement-breakpoint
CREATE TABLE "blend_flavorings" (
	"blend_id" integer NOT NULL,
	"flavoring_id" integer NOT NULL,
	CONSTRAINT "blend_flavorings_pk" PRIMARY KEY("blend_id","flavoring_id")
);
--> statement-breakpoint
CREATE TABLE "blend_ingredients" (
	"blend_id" integer NOT NULL,
	"ingredient_id" integer NOT NULL,
	CONSTRAINT "blend_ingredients_pk" PRIMARY KEY("blend_id","ingredient_id")
);
--> statement-breakpoint
CREATE TABLE "blend_manufacturers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "blend_manufacturers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"url" text,
	CONSTRAINT "blend_manufacturers_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "blend_packagings" (
	"blend_id" integer NOT NULL,
	"packaging_type_id" integer NOT NULL,
	CONSTRAINT "blend_packagings_pk" PRIMARY KEY("blend_id","packaging_type_id")
);
--> statement-breakpoint
CREATE TABLE "blend_type_categories" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "blend_type_categories_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"description" text NOT NULL,
	CONSTRAINT "blend_type_categories_description_unique" UNIQUE("description")
);
--> statement-breakpoint
CREATE TABLE "blend_types" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "blend_types_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"description" text NOT NULL,
	"blend_type_category_id" integer NOT NULL,
	CONSTRAINT "blend_types_description_unique" UNIQUE("description")
);
--> statement-breakpoint
CREATE TABLE "blends" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "blends_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"manufacturer_id" integer NOT NULL,
	"name" text NOT NULL,
	"blend_type_id" integer NOT NULL,
	"blend_cut_id" integer NOT NULL,
	"rating" numeric(3, 2),
	"tobacco_reviews_id" integer,
	"tobacco_reviews_rating" numeric(4, 2),
	"tobacco_reviews_url" text,
	"notes" text,
	"is_active" boolean DEFAULT true NOT NULL,
	CONSTRAINT "blends_manufacturer_name_unique" UNIQUE("manufacturer_id","name"),
	CONSTRAINT "blends_tobacco_reviews_id_unique" UNIQUE("tobacco_reviews_id"),
	CONSTRAINT "blends_rating_range" CHECK ("blends"."rating" IS NULL OR "blends"."rating" BETWEEN 1 AND 4)
);
--> statement-breakpoint
CREATE TABLE "cellar_items" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "cellar_items_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"blend_id" integer NOT NULL,
	"packaging_type_id" integer NOT NULL,
	"status_id" integer DEFAULT 20 NOT NULL,
	"quantity_grams" numeric(10, 2) DEFAULT 50 NOT NULL,
	"tin_date" timestamp with time zone DEFAULT now() NOT NULL,
	"opened_date" timestamp with time zone,
	"age_at_open_days" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "cellar_items_quantity_nonnegative" CHECK ("cellar_items"."quantity_grams" >= 0),
	CONSTRAINT "cellar_items_archived_quantity_zero" CHECK ("cellar_items"."status_id" <> 40 OR "cellar_items"."quantity_grams" = 0)
);
--> statement-breakpoint
CREATE TABLE "cellar_statuses" (
	"id" integer PRIMARY KEY NOT NULL,
	"description" text NOT NULL,
	CONSTRAINT "cellar_statuses_description_unique" UNIQUE("description")
);
--> statement-breakpoint
CREATE TABLE "countries" (
	"alpha2" char(2) PRIMARY KEY NOT NULL,
	"name" text NOT NULL,
	"alpha3" char(3)
);
--> statement-breakpoint
CREATE TABLE "flavorings" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "flavorings_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"description" text NOT NULL,
	CONSTRAINT "flavorings_description_unique" UNIQUE("description")
);
--> statement-breakpoint
CREATE TABLE "ingredients" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "ingredients_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"description" text NOT NULL,
	CONSTRAINT "ingredients_description_unique" UNIQUE("description")
);
--> statement-breakpoint
CREATE TABLE "maintenance_actions" (
	"id" integer PRIMARY KEY NOT NULL,
	"description" text NOT NULL,
	CONSTRAINT "maintenance_actions_description_unique" UNIQUE("description")
);
--> statement-breakpoint
CREATE TABLE "packaging_types" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "packaging_types_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"description" text NOT NULL,
	CONSTRAINT "packaging_types_description_unique" UNIQUE("description")
);
--> statement-breakpoint
CREATE TABLE "pipe_filters" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipe_filters_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"description" text NOT NULL,
	CONSTRAINT "pipe_filters_description_unique" UNIQUE("description")
);
--> statement-breakpoint
CREATE TABLE "pipe_finishes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipe_finishes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"description" text NOT NULL,
	CONSTRAINT "pipe_finishes_description_unique" UNIQUE("description")
);
--> statement-breakpoint
CREATE TABLE "pipe_maintenance_entries" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipe_maintenance_entries_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"pipe_id" integer NOT NULL,
	"maintenance_action_id" integer NOT NULL,
	"performed_at" timestamp with time zone DEFAULT now() NOT NULL,
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "pipe_manufacturers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipe_manufacturers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" text NOT NULL,
	"country_code" char(2),
	"url" text,
	CONSTRAINT "pipe_manufacturers_name_unique" UNIQUE("name")
);
--> statement-breakpoint
CREATE TABLE "pipe_materials" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipe_materials_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"description" text NOT NULL,
	CONSTRAINT "pipe_materials_description_unique" UNIQUE("description")
);
--> statement-breakpoint
CREATE TABLE "pipe_shapes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipe_shapes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"description" text NOT NULL,
	CONSTRAINT "pipe_shapes_description_unique" UNIQUE("description")
);
--> statement-breakpoint
CREATE TABLE "pipe_statuses" (
	"id" integer PRIMARY KEY NOT NULL,
	"description" text NOT NULL,
	CONSTRAINT "pipe_statuses_description_unique" UNIQUE("description")
);
--> statement-breakpoint
CREATE TABLE "pipes" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "pipes_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"manufacturer_id" integer NOT NULL,
	"name" text NOT NULL,
	"acquired_at" timestamp with time zone DEFAULT now() NOT NULL,
	"shape_id" integer NOT NULL,
	"is_bent" boolean NOT NULL,
	"pipe_material_id" integer NOT NULL,
	"stem_material_id" integer NOT NULL,
	"finish_id" integer NOT NULL,
	"length_mm" numeric(7, 2),
	"weight_g" numeric(7, 2),
	"bowl_diameter_mm" numeric(7, 2),
	"bowl_depth_mm" numeric(7, 2),
	"filter_id" integer NOT NULL,
	"status_id" integer DEFAULT 10 NOT NULL,
	"price" numeric(10, 2),
	"reference_url" text,
	"notes" text,
	CONSTRAINT "pipes_length_mm_positive" CHECK ("pipes"."length_mm" IS NULL OR "pipes"."length_mm" > 0),
	CONSTRAINT "pipes_weight_g_positive" CHECK ("pipes"."weight_g" IS NULL OR "pipes"."weight_g" > 0),
	CONSTRAINT "pipes_bowl_diameter_mm_positive" CHECK ("pipes"."bowl_diameter_mm" IS NULL OR "pipes"."bowl_diameter_mm" > 0),
	CONSTRAINT "pipes_bowl_depth_mm_positive" CHECK ("pipes"."bowl_depth_mm" IS NULL OR "pipes"."bowl_depth_mm" > 0),
	CONSTRAINT "pipes_price_nonnegative" CHECK ("pipes"."price" IS NULL OR "pipes"."price" >= 0)
);
--> statement-breakpoint
CREATE TABLE "sessions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "sessions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"occurred_at" timestamp with time zone DEFAULT now() NOT NULL,
	"pipe_id" integer NOT NULL,
	"cellar_item_id" integer NOT NULL,
	"notes" text,
	"function_score" integer,
	"flavor_score" integer,
	"is_break_in" boolean DEFAULT false NOT NULL,
	"deleted_at" timestamp with time zone,
	CONSTRAINT "sessions_function_score_range" CHECK ("sessions"."function_score" IS NULL OR "sessions"."function_score" BETWEEN 1 AND 4),
	CONSTRAINT "sessions_flavor_score_range" CHECK ("sessions"."flavor_score" IS NULL OR "sessions"."flavor_score" BETWEEN 1 AND 4)
);
--> statement-breakpoint
CREATE TABLE "stem_materials" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "stem_materials_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"description" text NOT NULL,
	CONSTRAINT "stem_materials_description_unique" UNIQUE("description")
);
--> statement-breakpoint
CREATE TABLE "supplies" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "supplies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"description" text NOT NULL,
	"units_per_package" integer NOT NULL,
	"packages_on_hand" integer DEFAULT 0 NOT NULL,
	CONSTRAINT "supplies_units_per_package_positive" CHECK ("supplies"."units_per_package" > 0),
	CONSTRAINT "supplies_packages_on_hand_nonnegative" CHECK ("supplies"."packages_on_hand" >= 0)
);
--> statement-breakpoint
ALTER TABLE "blend_flavorings" ADD CONSTRAINT "blend_flavorings_blend_id_blends_id_fk" FOREIGN KEY ("blend_id") REFERENCES "public"."blends"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blend_flavorings" ADD CONSTRAINT "blend_flavorings_flavoring_id_flavorings_id_fk" FOREIGN KEY ("flavoring_id") REFERENCES "public"."flavorings"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blend_ingredients" ADD CONSTRAINT "blend_ingredients_blend_id_blends_id_fk" FOREIGN KEY ("blend_id") REFERENCES "public"."blends"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blend_ingredients" ADD CONSTRAINT "blend_ingredients_ingredient_id_ingredients_id_fk" FOREIGN KEY ("ingredient_id") REFERENCES "public"."ingredients"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blend_packagings" ADD CONSTRAINT "blend_packagings_blend_id_blends_id_fk" FOREIGN KEY ("blend_id") REFERENCES "public"."blends"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blend_packagings" ADD CONSTRAINT "blend_packagings_packaging_type_id_packaging_types_id_fk" FOREIGN KEY ("packaging_type_id") REFERENCES "public"."packaging_types"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blend_types" ADD CONSTRAINT "blend_types_blend_type_category_id_blend_type_categories_id_fk" FOREIGN KEY ("blend_type_category_id") REFERENCES "public"."blend_type_categories"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blends" ADD CONSTRAINT "blends_manufacturer_id_blend_manufacturers_id_fk" FOREIGN KEY ("manufacturer_id") REFERENCES "public"."blend_manufacturers"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blends" ADD CONSTRAINT "blends_blend_type_id_blend_types_id_fk" FOREIGN KEY ("blend_type_id") REFERENCES "public"."blend_types"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "blends" ADD CONSTRAINT "blends_blend_cut_id_blend_cuts_id_fk" FOREIGN KEY ("blend_cut_id") REFERENCES "public"."blend_cuts"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cellar_items" ADD CONSTRAINT "cellar_items_blend_id_blends_id_fk" FOREIGN KEY ("blend_id") REFERENCES "public"."blends"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cellar_items" ADD CONSTRAINT "cellar_items_packaging_type_id_packaging_types_id_fk" FOREIGN KEY ("packaging_type_id") REFERENCES "public"."packaging_types"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "cellar_items" ADD CONSTRAINT "cellar_items_status_id_cellar_statuses_id_fk" FOREIGN KEY ("status_id") REFERENCES "public"."cellar_statuses"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipe_maintenance_entries" ADD CONSTRAINT "pipe_maintenance_entries_pipe_id_pipes_id_fk" FOREIGN KEY ("pipe_id") REFERENCES "public"."pipes"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipe_maintenance_entries" ADD CONSTRAINT "pipe_maintenance_entries_maintenance_action_id_maintenance_actions_id_fk" FOREIGN KEY ("maintenance_action_id") REFERENCES "public"."maintenance_actions"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipe_manufacturers" ADD CONSTRAINT "pipe_manufacturers_country_code_countries_alpha2_fk" FOREIGN KEY ("country_code") REFERENCES "public"."countries"("alpha2") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipes" ADD CONSTRAINT "pipes_manufacturer_id_pipe_manufacturers_id_fk" FOREIGN KEY ("manufacturer_id") REFERENCES "public"."pipe_manufacturers"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipes" ADD CONSTRAINT "pipes_shape_id_pipe_shapes_id_fk" FOREIGN KEY ("shape_id") REFERENCES "public"."pipe_shapes"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipes" ADD CONSTRAINT "pipes_pipe_material_id_pipe_materials_id_fk" FOREIGN KEY ("pipe_material_id") REFERENCES "public"."pipe_materials"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipes" ADD CONSTRAINT "pipes_stem_material_id_stem_materials_id_fk" FOREIGN KEY ("stem_material_id") REFERENCES "public"."stem_materials"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipes" ADD CONSTRAINT "pipes_finish_id_pipe_finishes_id_fk" FOREIGN KEY ("finish_id") REFERENCES "public"."pipe_finishes"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipes" ADD CONSTRAINT "pipes_filter_id_pipe_filters_id_fk" FOREIGN KEY ("filter_id") REFERENCES "public"."pipe_filters"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "pipes" ADD CONSTRAINT "pipes_status_id_pipe_statuses_id_fk" FOREIGN KEY ("status_id") REFERENCES "public"."pipe_statuses"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_pipe_id_pipes_id_fk" FOREIGN KEY ("pipe_id") REFERENCES "public"."pipes"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_cellar_item_id_cellar_items_id_fk" FOREIGN KEY ("cellar_item_id") REFERENCES "public"."cellar_items"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "cellar_items_blend_id_idx" ON "cellar_items" USING btree ("blend_id");--> statement-breakpoint
CREATE INDEX "cellar_items_status_id_idx" ON "cellar_items" USING btree ("status_id");--> statement-breakpoint
CREATE INDEX "pipe_maintenance_entries_pipe_performed_at_idx" ON "pipe_maintenance_entries" USING btree ("pipe_id","performed_at");--> statement-breakpoint
CREATE INDEX "pipes_status_id_idx" ON "pipes" USING btree ("status_id");--> statement-breakpoint
CREATE INDEX "sessions_pipe_occurred_at_idx" ON "sessions" USING btree ("pipe_id","occurred_at");--> statement-breakpoint
CREATE INDEX "sessions_cellar_item_occurred_at_idx" ON "sessions" USING btree ("cellar_item_id","occurred_at");